<?php 
return [
'cnf_appname' 			=> 'Bangladesh Infrastructure Finance Fund Limited (BIFFL)',
'cnf_appdesc' 			=> 'Bangladesh Infrastructure Finance Fund Limited (BIFFL)',
'cnf_comname' 			=> 'Bangladesh Infrastructure Finance Fund Limited (BIFFL)',
'cnf_email' 			=> 'biffl@techhut.com.bd',
'cnf_metakey' 			=> 'Bangladesh Infrastructure Finance Fund Limited (BIFFL)',
'cnf_metadesc' 		=> 'Bangladesh Infrastructure Finance Fund Limited (BIFFL)',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'false',
'cnf_front' 			=> 'true',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6LersA4iAAAAAMLvFwMFt-ufXR8yWhWdLc5Ijsy-',
'cnf_recaptchaprivatekey' => '6LersA4iAAAAANSVZqrQJdeYEbcgnbmlmAQS6bd_',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> 'AIzaSyAayRr-0yZ1ejGGX6l--XDVbHWU85wPj9U',
'cnf_date' 			=> 'd-m-y',
];
